export const ADD_PUBLICACION = 'ADD_PUBLICACION';
export const DELETE_PUBLICACION = 'DELETE_PUBLICACION';
export const UPDATE_PUBLICACION = 'UPDATE_PUBLICACION';
export const SET_PUBLICACIONES = 'SET_PUBLICACIONES';
